apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: europe-west1-docker.pkg.dev/infra3-demydenko-oleksii/docker-repo-texttoimage-project/app1:latest
          env:
            - name: APP1_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: APP_ADDRESS
              value: app1-service.default
          ports:
            - containerPort: 8080
